<div class="row">

    <div class="span6">
        <div class="centered">
            <h2>Ticket</h2>
        </div>

        <form method="post" id="projectform" action="<?php echo $this->baseUrl();?>manage/update"
              class="form-horizontal">
            <input type='hidden' name='id' value='<?=$this->ticket->id;?>'/>
            <fieldset>

                <div class="row">
                    <div class="span6">

                        <div class="control-group">
                            <label class="control-label" for="input01">Ticket subject</label>

                            <div class="controls">
                                <input type="text" class="projectinput" placeholder="Ticket subject"
                                       id="input01" name="subject" value="<?=$this->escape($this->ticket->subject);
								?>"/>

                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="input05">Details</label>

                            <div class="controls">
                                <textarea class="projectinput" placeholder="Instructions for the team here"
                                          id="description"
                                          name="description"><?php echo $this->escape($this->ticket->description);
									?></textarea>


                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="projectcontributors">Technicians</label>

                            <div class="controls">
								<?php foreach($this->technicians as $t) { ?>
								<?php
									$check = "";
//									if(in_array($t, $this->ticket->ownAccount)) { $check = " checked"; }
								?>
<input type='checkbox' name='tech[<?=$t->id;?>]'/> <label for="tech[<?=$t->id;?>]"><?=$t->name;?></label><br/>
	<?php } ?>
                            </div>
                        </div>


                        <div class="centered">
                            <input type='submit' value='Update' class=' btn btn-info'/>
                        </div>

                    </div>
                </div>
                <div class="row">
                    <div class="span6 centered">

                    </div>
                </div>
            </fieldset>

        </form>

    </div>


</div>

<script>
    function preview() {
        $.post("<?=$this->baseUrl();?>project/preview/", $("#projectform").serialize(), function (data) {
//                document.getElementById("iframepreview").contentWindow.location.reload(true);
            $('#iframepreview').attr('src', $('#iframepreview').attr('src'));

            return false;

        });
    }

    function toggleselect(e) {
        var t = e.target.options[e.target.options.selectedIndex].value;
        var id = e.target.id.replace("select_", "");
        var oid = "optiongroup_" + id;
        if (t == 'list') {
            $("." + oid).show();
        } else {
            $("." + oid).hide();
        }
    }

    function clearlink(e) {
        var id = e.target.id.replace("clear_", "");
        var sid = "select_" + id;
        var nid = "name_" + id;
        var oid = "optiongroup_" + id;
        jQuery("#" + sid).val(1);
        jQuery("#" + nid).val('');
        $("." + oid).hide();
        preview();
    }

    $(".selectbox").change(function (e) {
        toggleselect(e)
    });
    $(".clearlink").click(function (e) {
        clearlink(e)
    });
    $(".projectinput").blur(function (e) {
        preview()
    });
    $(document).ready(preview());
</script>
