<div class="container aboutpage">

    <div class="row">
        <div class="span12">
            <div class="pull-right">
                <img src="<?=$this->baseUrl();?>images/note1.png" width="150"/>
            </div>
            <h2>
                "How can we simplify mobile data collection?"

            </h2>
            <br/>

            <p>
                <b>That</b> was our driving question in early 2012.
                Juggling multiple software installs, expensive GPS units (often requiring training) and
                aggregating data on tight deadlines are all common problems faced by a growing number
                of professionals.
            </p>

            <p>&nbsp;</p>

            <h2>The solution - Field Flag</h2>

            <p>
                Field Flag is the result of combining our experiences with mobile data collection and a drive
                towards simplicity.
            </p>
            <br/>
        </div>
    </div>


    <div class="row">

        <div class="span4">

            <h3>
                Business experts, not GIS experts
            </h3>


            <p>
                Most professionals today that have "in the field" data collection needs are
                not GIS experts - they just need to get their job done.
                </p>
            <p>
                We made Field Flag for them.
            </p>
        </div>


        <div class="span4">

            <h3>Consumer-level smartphones</h3>

            <p>
                Android and iOS smartphones and tablets are everywhere, and many people are already familiar with how
                to operate them. Field Flag was designed with web-enabled smartphones and tablets in mind
                from day one, and is optimized for those devices.
            </p>

        </div>
        <div class="span4">
            <h3>Modern web technologies</h3>

            <p>
                By using web technologies, Field Flag users can send their data back in real time. Information can be
                exported from FieldFlag.com in Excel or CSV formats for archiving or integration with other
                applications.
            </p>
        </div>
    </div>


    <hr/>


    <div class="row">
        <div class="span12">
            <p>&nbsp;</p>

            <h2>The Team</h2>
            <br/>
        </div>

        <div class="span6">
            <h3>Kate Lyndegaard</h3>

            <p>
                Kate is currently pursuing her Masters degree in GIS at Penn State.
                Over the past several years,
                she's held positions with various local government
                organizations where she's had the opportunity to become involved in a
                variety of different community projects each with specific GIS needs
                and solutions. In her spare time, Kate trains at the gym daily and plays golf.
                She also enjoys traveling to Denmark, and learning the Danish language.

            </p>
        </div>


        <div class="span6">
            <h3>Michael Kimsal</h3>

            <p>
                Michael has over 15 years of web development
                experience, working in industries including
                education, finance, manufacturing and logistics.
                He produces the webdevradio podcast series for
                developers, and is a speaker at regional
                technology conferences.
            </p>
        </div>

    </div>

    <hr/>
    <div class="row">

        <div class="span12">
            <h2>Contact</h2>

            <p>
                Contact us at info@fieldflag.com for more information.
            </p>
        </div>
    </div>

</div>

