

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
<?=$this->sidebarinstructions();?>
        </div><!--/span-->
        <div class="span9">
          <div class= "well hero-unit">
            <br/>
<h1>Add a project
</h1>
<hr>
<p> The first step towards creating your own, customized data collection project is to name your new project. </p><br>
<p>To add a project, navigate to the Projects link at the top of the page.
 </p><br>
 <p><img class="right" width="1000" height="108" src="<?=$this->baseUrl();?>appcase\img\project.png" alt="placeholder"/> </p> </br>
<p>Next, enter the name of your new project and click the Add button next to it: </p><br>
<p><img class="right" width="1000" height="188" src="<?=$this->baseUrl();?>appcase\img\addproject.png" alt="placeholder"/> </p> </br>
<p>The name of your new project will appear in the Name column in the table below. </p><br />
<hr>

                     </div>
         </div><!--/span-->
      </div><!--/row-->
	


    </div><!--/.fluid-container-->
        

