

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
            <?=$this->sidebarinstructions();?>
        </div><!--/span-->
        <div class="span9">
          <div class= "well hero-unit">
            <br/>
<h1>Collect Data</br>
</h1>
<hr>
<p> Now you and your team are ready to collect data. Simply click the highlighted email link next to your project name, and a link to your data collection project will be mailed to each contributors.
 </p><br>
<p>To begin collecting data, recipients must click on the link in their email. It's easy:
</p></br>
<p>1. Click 'Add Marker'
</p></br>
<p>2. Drag your marker to your chosen location
</p></br>
<p>3. Click 'Proceed'
</p></br>
<p>4. Fill in attribute information using your form
</p></br>
<p>5. Click 'Submit'
</p></br>
<p>6. Collect another point, and repeat the process
</p></br>

<hr>

                     </div>
         </div><!--/span-->
      </div><!--/row-->


    </div><!--/.fluid-container-->
        
