
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
<?=$this->sidebarinstructions();?>
        </div><!--/span-->
        <div class="span9">
          <div class= "well hero-unit">
            <br/>
<h1>Create a data entry form</br>
</h1>
<hr>
<p> Once you have added a new project, click the highlighted edit link next to your project name. This will bring you to a page that will allow you to enter information about the points of interest that you would like to collect in the field. 
 </p><br>
<p><img class="right" width="1000" height="332" src="<?=$this->baseUrl();?>appcase\img\editproject.png" alt="placeholder"/> </p> </br>
<p>The next step is to add a description. Continue by adding the email addresses of your field agents so that they can receive a link to your customized web application.
</p></br>
<p><img class="right" width="1000" height="328" src="<?=$this->baseUrl();?>appcase\img\email.png" alt="placeholder"/> </p> </br>
<p>Field #1 represents the first attribute that your field agents will collect for each point.  First, enter the name of this field. 
</p></br>
<p>Next, select the type of field this attribute represents. Will a number, a photo, or text be entered by your field agents? Select the List option if you would like to create a dropdown menu of preset categories.
</p></br>
<p><img class="right" width="1000" height="218" src="<?=$this->baseUrl();?>appcase\img\field1.png" alt="placeholder"/> </p> </br>
<p>Enter the categories you would like displayed in your dropdown menu next to Options.
</p></br>
<p>When you are finished, click the Update button at the bottom of the page to save your data entry form. 
</p></br>

<hr>

                     </div>
         </div><!--/span-->
      </div><!--/row-->

    </div><!--/.fluid-container-->
        
