

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
<?=$this->sidebarinstructions();?>
        </div><!--/span-->
        <div class="span9">
          <div class= "well hero-unit">
            <br/>
<h1>Deploy your project</br>
</h1>
<hr>
<p> Facilitating the workflows of your field agents just got easier! Deploy your project instantly across multiple devices to reduce error and ensure that everyone on your team is on the same page.
 </p><br>
<p>Just click the highlighted email link next to your project name on the main Projects page. A link to your customized data collection project will be emailed to each of the addresses listed under the Contributors column. Once received, your contributors will simply click on the link to open the project and begin collecting data.
</p></br>
<p><img class="right" width="1000" height="332" src="<?=$this->baseUrl();?>appcase\img\deploy.png" alt="placeholder"/> </p> </br>
<hr>

                     </div>
         </div><!--/span-->
      </div><!--/row-->
	

    </div><!--/.fluid-container-->
        

