
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
            <?=$this->sidebarinstructions();?>
        </div><!--/span-->
        <div class="span9">
          <div class= "well hero-unit">
            <br/>
<h1>Edit a data entry form</br>
</h1>
<hr>
<p> You can edit your project's data entry form at any point during your project. Just click the highlighted edit link next to your project name on the main Projects page.
 </p><br>
 <p><img class="right" width="1000" height="332" src="<?=$this->baseUrl();?>appcase\img\editproject.png" alt="placeholder"/> </p> </br>
<p>Remember, if you edit a project's data entry form, and you have already deployed the project across multiple devices, you will have to re-send the application link to your field team so that they can access the updated project entry form.
</p></br>

<hr>

                     </div>
         </div><!--/span-->
      </div><!--/row-->
	


    </div><!--/.fluid-container-->
        
