<div class="container aboutpage">

    <div class="row">
        <div class="span12">

            <h2>
                How can Field Flag help you?
            </h2>
            <br/>

            <p>
              Take a look below at some example use cases for Field Flag.
            </p>

            <p>&nbsp;</p>


        </div>
    </div>


    <div class="row">

        <div class="span8">

            <h3>
                Ava, GIS Director
            </h3>
            <h3>Monitoring the usability of city bike racks</h3>


            <p>
                Ava works at a local regional planning office that provides technical support
                to the city and surrounding areas.
            </p>
            <p>
                An assessment of the usability status and user rate of 200 local bike racks has been
                requested and will be addressed by her staff over the course of the next 12 months.
            </p>
            <p>
                The assessment will require members of her team to periodically monitor the bike racks to track usage.
                Once field agents locate a bike rack, Field Flag enables them to enter information about
                its condition, use rate, and any other variables Ava has identified in her custom data entry form.
                </p>
            <p>
                Using Field Flag on existing, GPS-enabled smartphone devices, Ava's team will be able to
                commence work on the project immediately.
</p>
            <p>
                With minimal training, and no costly hardware procurements, the project is off to great start.


                </p>

        </div>

        <div class="span4 centered">
            <h3>&nbsp;</h3>
            <h3>&nbsp;</h3>
            <h3>&nbsp;</h3>
            <h3>&nbsp;</h3>
            <img width="256" src="<?=$this->baseUrl();?>images/stories_bike.jpg"/>
        </div>
</div>

<div class="row">&nbsp;</div>
<div class="row">&nbsp;</div>

    <div class="row">

        <div class="span4 centered">
            <h3>&nbsp;</h3>
            <h3>&nbsp;</h3>
            <img width="256" src="<?=$this->baseUrl();?>images/stories_land.jpg"/>
        </div>

        <div class="span8">

            <h3>
                Henry, Owner
            </h3>
            <h3>Document on-site job estimates</h3>


            <p>
                Henry is the owner of EcoLandscaping, a mid-sized company which serves both private and commercial clients.
            </p>
            <p>
                The company is growing, and their paper-based system used to report job estimates is becoming increasing difficult to manage.
                Henry is looking for a solution that will enable his employees to document client requests while they are on-site and update office personnel in real-time.
            </p>
            <p>
                With Field Flag, Henry has the information he needs to better manage the services his company provides.

            </p>


        </div>

    </div>


    <div class="row">&nbsp;</div>
    <div class="row">&nbsp;</div>



    <div class="row">

        <div class="span8">

            <h3>
                Elsa, Professor of Archeology
            </h3>
            <h3>Survey local archaeology site</h3>


            <p>
                Elsa is a Professor of Archaeology at a local college. 
                In collaboration with a local Tribal Association, Elsa plans to begin surveying local sites to document cultural features and visible artifacts. 
                </p>
            <p>
                Student involvement is an integral part of planned research efforts, and Elsa is searching for a solution that will enable her to task students with field data collection. 
             </p>
            <p>
                Field Flag will allow Elsa to leverage students' familiarity with smartphone devices and include a greater number of students on the project.
                </p>

        </div>

        <div class="span4 centered">
            <h3>&nbsp;</h3>
            <h3>&nbsp;</h3>
            <img width="256" src="<?=$this->baseUrl();?>images/stories_dig.jpg"/>
        </div>
</div>

<div class="row">&nbsp;</div>
<div class="row">&nbsp;</div>

    <div class="row">

        <div class="span4 centered">
            <h3>&nbsp;</h3>
            <h3>&nbsp;</h3>
            <img width="256" src="<?=$this->baseUrl();?>images/stories_lamp.jpg"/>
        </div>

        <div class="span8">

            <h3>
                Samantha, AICP
            </h3>
            <h3>
                Perform asset inventory of city light poles
            </h3>


            <p>
                Samantha is employed by her local city government. Citizen reports have recently drawn attention to a number of non-functional street lights. 
                </p>
            <p>
                Without an existing inventory of the physical location of street lights throughout the city, plans to address the issue have reached a standstill. 
                Samantha has been put in charge of conducting an asset inventory of the over 500 light poles citywide. 
                </p>
            <p>
                The data collection effort will enable planners to implement efficient maintenance schedules and monitor the condition of city assets.
            </p>


        </div>

    </div>






    <hr/>
    <div class="row">

        <div class="span12">
            <h2>Contact</h2>

            <p>
                Contact us at info@fieldflag.com for more information.
            </p>
        </div>
    </div>

</div>

