

    <div class="container">
      <div class="row">

          <div class="container">
              <div class="row-fluid">
                  <div class="hero-unit">
                      <h1>How Field Flag is being used.</h1>
                      <p>The opportunities are endless. Use Field Flag to collect any type of data in the field using your smartphone, or other device. Check out the following use cases to learn more about what other people are doing with Field Flag.</p>
                  </div>
              </div><!--/row-->
              <br/>
              <hr />
              <h1>Brightwing Energy LLC</br>
              </h1>
              <h2>Ground locate and verify 250 electricity meters</h2>
              <p><img class="right" width="140" height="120" src="http://placehold.it/140x120" alt="placeholder"/> </p> </br> <em>Daniel Arneman: Consultant, Brightwing Energy LLC</em> </br>
              <p> Daniel Arneman, a consultant at Brightwing Energy LLC, was recently hired to ground locate and verify 250 electricity meters spread over a metropolitan area in North Carolina. The completion of the task required the use of multiple devices in order for the team to:.</p><br>
              <ol>
                  <li>Locate an electricity meter based on GPS coordinates</li>
                  <li>Verify the status of the electricity meter</li>
                  <li>Attach a picture of the meter to its recorded location</li>
              </ol>
              <p>The use of Field Flag makes it possible to consolidate the entire process into one, seamless workflow, from start to finish. Field Flag enables users to:</p><br/>
              <ol>
                  <li>Plan an optimal route based on either GPS coordinates or address</li>
                  <li>Split the project up into several sub-projects – a feature beneficial for large scale data collection projects</li>
                  <li>Verify the status of an electricity meter, attach a picture and upload the georeferenced point to a server</li>
              </ol>
              <p>Field Flag is designed to facilitate high volume data collection projects which require the logging of attribute information.
                  Field Flag has an intuitive interface
                  which eliminates the need for training, and makes adding new people to the project easy.</p><br/>
              <p>Sign up today and try Field Flag on your next data collection project.</p><br/>

              <blockquote>This is GPS data capture made easy. Looking for customizable data collection using off-the-shelf mobile devices? Field Flag has got you covered.
                  <small>By Michael from Youngsville, NC</small>
              </blockquote>
              <br />
              <hr>




              <footer>
                  <p>&copy; fieldflag team 2012</p>
              </footer>


      </div><!--/row-->


    </div><!--/.fluid-container-->


