
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
<?=$this->sidebarinstructions();?>
        </div><!--/span-->
        <div class="span9">
          <div class= "well hero-unit">
            <br/>
<h1>Export your data</br>
</h1>
<hr>
<p>To export data, navigate to the main Project page. Under Existing projects,
    click the highlighted export link next to your project name to automatically download a .csv file containing your project data.
</p></br>
<p><img class="right" width="1000" height="332" src="<?=$this->baseUrl();?>appcase\img\export.png" alt="placeholder"/> </p> </br>
<hr>

                     </div>
         </div><!--/span-->
      </div><!--/row-->
	


    </div><!--/.fluid-container-->
        
