
    <div class="container">
      <div class="row">
                <div class="tabbable tabs-left">
                    <div class="span2">
                    <ul class="nav nav-tabs">
                        <li><a href="#tab1" data-toggle="tab">Add a project</a>
                        </li>
                        <li><a href="#tab2" data-toggle="tab">Create a data entry form</a>
                        </li>
                        <li><a href="#tab3" data-toggle="tab">Edit a data entry form</a>
                        </li>
                        <li><a href="#tab4" data-toggle="tab">Deploy your project</a>
                        </li>
                        <li><a href="#tab5" data-toggle="tab">Collect data</a>
                        </li>
                        <li><a href="#tab6" data-toggle="tab">View your data</a>
                        </li>
                        <li><a href="#tab7" data-toggle="tab">Export you data</a>
                        </li>
                    </ul>
                    </div>

                    <div class="tab-content">
                        <div class="tab-pane" id="tab1">
                            <div class="span9 offset3">
                                    <h1>Add a project</h1>
                                    <hr>
                                    <p> The first step towards creating your own, customized data collection project is to name your new project. </p><br>
                                    <p>To add a project, navigate to the Projects link at the top of the page.
                                    </p><br>
                                    <p><img class="right" width="1000" height="108" src="<?=$this->baseUrl();?>appcase\img\project.png" alt="placeholder"/> </p> </br>
                                    <p>Next, enter the name of your new project and click the Add button next to it: </p><br>
                                    <p><img class="right" width="1000" height="188" src="<?=$this->baseUrl();?>appcase\img\addproject.png" alt="placeholder"/> </p> </br>
                                    <p>The name of your new project will appear in the Name column in the table below. </p><br />
                                    <hr>
                                </div><!--/span-->
                        </div><!--/tab pane-->

                        <div class="tab-pane" id="tab2">
                            <p>Howdy, I'm in Section 2.</p>
                        </div>
                        <div class="tab-pane" id="tab3">
                            <p>Howdy, I'm in Section 2.</p>
                        </div>
                        <div class="tab-pane" id="tab4">
                            <p>Howdy, I'm in Section 2.</p>
                        </div>
                        <div class="tab-pane" id="tab5">
                            <p>Howdy, I'm in Section 2.</p>
                        </div>
                        <div class="tab-pane" id="tab6">
                            <p>Howdy, I'm in Section 2.</p>
                        </div>
                        <div class="tab-pane" id="tab7">
                            <p>Howdy, I'm in Section 2.</p>
                        </div>
                </div><!--/tab content-->
      </div><!--/tabbable-->

        <div class="span10 offset3">
            <div class= "well hero-unit">
                <h1>How Field Flag Works.</h1>
                <p>Follow the links in the sidebar for help with getting started.</p>
                <br/>
                <hr />
            </div><!--/hero-->
        </div><!--/span-->

      </div><!--/row-->
	
      <hr>

      <footer>
        <p>&copy; fieldflag team 2012</p>
      </footer>

    </div><!--/.container-->
        

