

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">

<?=$this->sidebarinstructions();?>
        </div><!--/span-->
        <div class="span9">
          <div class= "well hero-unit">
            <br/>
<h1>View your data</br>
</h1>
<hr>
<p> Under Existing projects on the main Project page, you will see a list of your current data collection projects. 
 </p><br>
<p>To view your data, click the highlighted number in the Responses column of your project. This number represents the number of points collected on your project.
</p></br>
<p><img class="right" width="1000" height="332" src="<?=$this->baseUrl();?>appcase\img\view.png" alt="placeholder"/> </p> </br>
<p>On the Responses page you are able to view all of the points that have been captured on your project. A list of all data points collected will display in spreadsheet format, including information such as the time each was entered, the agent who entered it, and the GPS coordinates. The map inset to the left displays the location of the point captured. Use this page to easily keep track of all project data collected in the field.
</p></br>

<hr>

                     </div>
         </div><!--/span-->
      </div><!--/row-->


    </div><!--/.fluid-container-->
        

