<?php $this->headTitle('Register'); ?>

<?php if ($e = $this->form->getErrorMessages()) { ?>
    <?php foreach ($e as $error) { ?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert"> x </a>
            <?php echo $error;?>
        </div>
    <?php } ?>
<?php } ?>



<?php echo $this->form->setAction($this->url()); ?>


<fb:login-button id="loginbutton" style="display:none;"
				 on-login="document.location.href='<?=$this->fullUrl();?>register/facebook';"
				 registration-uri="<?=$this->fullUrl();?>register/facebook" ></fb:login-button>


<script>
   function handleResponseChange(response) {
           document.body.className = response.authResponse ? 'connected' : 'not_connected';

           if (response.authResponse) {
             console.log(response);
           }
         }
 </script>
<script>

  window.fbAsyncInit = function() {
    // init the FB JS SDK
    FB.init({
      appId      : '<?=$this->facebookAppId();?>', // App ID from the App Dashboard
      channelUrl : '//kimsal.pagekite.me/tg2/channel.html', // Channel File for x-domain communication
      status     : true, // check the login status upon init?
      cookie     : true, // set sessions cookies to allow your server to access the session?
      xfbml      : true  // parse XFBML tags on this page?
    });

    // Additional initialization code such as adding Event Listeners goes here
	  FB.getLoginStatus(function(response) {
	    // this will be called when the roundtrip to Facebook has completed
		  if(response.status=="connected")
		  {
			  document.getElementById("loginbutton").style="display:none";
			  document.location.href="<?=$this->fullUrl();?>register/facebook";
//			  alert('hidden');
		  }
		  if(response.status=="not_authorized")
		  {
			  document.getElementById("loginbutton").style="display:block";
//			  alert('block');
		  }
		  if(response.status=="unknown")
		  {
			  document.getElementById("loginbutton").style="display:block";
//			  alert('unknown');
		  }

	  }, true);
  };

  // Load the SDK's source Asynchronously
  // Note that the debug version is being actively developed and might
  // contain some type checks that are overly strict.
  // Please report such bugs using the bugs tool.
  (function(d, debug){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all" + (debug ? "/debug" : "") + ".js";
     ref.parentNode.insertBefore(js, ref);
   }(document, /*debug*/ false));
</script>