<h2>Define a project</h2>
<div class="row">
<div class="span6">
<p>
At the heart of FieldFlag is a project - your definition about the data you wish to capture at each location, and who needs to capture this information.

</p>
<p>
Each project can collect a configurable amount of defined information - whether you need to capture freeform text, 
numeric ranges, values from predefined lists, or even photographs, FieldFlag has you covered!
</p>
</div>
<div class="span6">
    <div id="myCarousel" class="carousel">
    <!-- Carousel items -->
    <div class="carousel-inner">
<div class="active item">
<img src="<?=$this->baseUrl();?>images/project1.png" alt="project 1 sample" width="320"/>
</div>
<div class="item">
<img src="<?=$this->baseUrl();?>images/field1.png" alt="project 1 sample" width="320"/>
</div>
<div class="item">
<img src="<?=$this->baseUrl();?>images/field2.png" alt="project 1 sample" width="320"/>
</div>
<div class="item">
<img src="<?=$this->baseUrl();?>images/field3.png" alt="project 1 sample" width="320"/>
</div>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
</div>
</div>

<h2>Email participants</h2>
<p>

</p>
<script>
    $('.carousel').carousel({
    interval: 4000
    })
</script>
