<div class="container-fluid">

<div class="hero-unit">
<div class="row">

	<div class="span6" style="float:left;">
		<h1>
		Easy to use<br/>GPS data capture
		</h1>
<br/>
<h2>
Customizable data capture using off-the-shelf mobile devices.
</h2>
	</div>

	<div class="span4">
		<img src="<?=$this->baseUrl();?>iphone1.png" width="145" style="float:left; margin-right: .2em;"/>
		<img src="<?=$this->baseUrl();?>iphone2.png" width="145" style="float:left;"/>
	</div>

</div>

</div>

</div>

<div class="container">

<div class="row">
<div class="span4">
&nbsp;
</div>
<div class="span4">
<form method='post' action="<?=$this->baseUrl();?>index/post">
<h2>
Join our mailing list!
</h2>
<input type='text' name='email'/>
<input type='submit' value='Join!' class='btn btn-primary'/>

</form>
</div>


<div class="span4">
&nbsp;
</div>




<!--
<div class="container">

<div class="row">

<div class="span1">
&nbsp;
</div>

<div class="span4">
	<h3>Here</h3>
</div>

<div class="span4">
	<h3>Here</h3>
</div>

<div class="span3">
	<h3>Here</h3>
</div>

</div>
</div>
-->
