<?php $this->headTitle('Login'); ?>
<?php if ($e = $this->errors) { ?>
    <?php foreach ($e as $error) { ?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert"> x </a>
            <?php echo $error;?>
        </div>
    <?php } ?>
<?php } ?>
<div class="row">
<?php echo $this->form->setAction($this->url()); ?>
</div>
<div class="row">
    <div class="container">
        <a href="<?=$this->baseUrl();?>auth/forgot">forgot your password?</a>
    </div>
</div>
