<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->allcss(); ?>
</head>
<body>
<div id="doc3" class="yui-t2">
	<div id="hd" role="banner">
<div id="topname">
		<span id="name1">ZF</span><span id="name2">Kit</span> - the zend framework starter kit
</div>
<div id="loggedin">
<?php echo $this->loggedInAs(); ?>
</div>
	</div>
	<div id="bd">
			<div id="yui-main">
					<div class="yui-b">
							<div role="contentinfo" class="yui-g" id="content">
								<?php echo $this->layout()->content ?>
							</div>
					</div>
			</div>
			<div id="menu" role="navigation" class="yui-b">
				<?php echo $this->navigation()->menu();?>
			</div>
	</div>
	<div id="ft" role="contentinfo">
		<p><a href="http://zfkit.com">zfkit.com</a></p>
	</div>
</div>
    <?php  echo $this->inlineScript() ?>
</body>
</html>
