<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><?php echo $this->title;?></title>
    <meta name="description" content="<?php echo $this->description;?>">
    <meta name="author" content="">

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
	<link rel="stylesheet" href="<?=$this->baseUrl();?>/css/<?=$this->theme;?>.bootstrap.min.css"/>
	<link rel="stylesheet" href="<?=$this->baseUrl();?>/css/05_main.css"/>
    <style type="text/css">
      body {
        padding-top: 40px; /* 40px to make the container go all the way to the bottom of the topbar */
      }
      
    </style>

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">

    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="#">Site</a>

          <ul class="nav">
<li><a href="<?=$this->baseUrl();?>">Home</a></li>
          </ul>
<?php if(!$this->loggedIn()) : ?>
          <form method="post" action="<?php echo $this->baseUrl();?>auth" class="pull-right topform">
            <input class="topinput input-small" type="text"  name="username" placeholder="Username">

            <input class="topinput input-small" type="password" name="password" placeholder="Password">
            <input class="btn blacktext" name="topbtn" type="submit" value="Sign in"/>
            <input class="btn blacktext" name="topbtn" type="submit" value="Register"/>
          </form>
<?php else : ?>
<div class="pull-right loggedin">
Welcome <?php echo $this->loggedInAs()->username; ?>
 &nbsp; 
<a href="<?php echo $this->baseUrl();?>auth/logout">Log out</a>
<?php endif; ?>
</div>

        </div>
      </div>
    </div>

    <div class="container">
<?php echo $this->flashMessages();?>
      <div class="content">
        <div class="page-header">
          <h1><?php echo $this->pageTitle ?: "page"; ?> 
          <small><?php echo $this->pageSubTitle ?: ""; ?> </small></h1>
        </div>
        <div class="row">

          <div class="span14">

			<?php echo $this->layout()->content; ?>
 
          </div>
        </div>
      </div>

      <footer>
	  <p>&copy; fosterburgess <?=date("Y");?></p>

      </footer>

    </div> <!-- /container -->

  </body>
</html>
