<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?php echo $this->title;?></title>
    <meta name="description" content="<?php echo $this->description;?>">
    <meta name="author" content="">



    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <script src='<?=$this->baseUrl();?>js/wax6beta/ext/leaflet.js' type='text/javascript'></script>
    <script src='<?=$this->baseUrl();?>js/wax6beta/dist/wax.leaf.js' type='text/javascript'></script>
    <link href='<?=$this->baseUrl();?>js/wax6beta/ext/leaflet.css' rel='stylesheet' type='text/css'/>
    <link href='<?=$this->baseUrl();?>js/wax6beta/theme/controls.css' rel='stylesheet' type='text/css'/>
    <script src="<?=$this->baseUrl();?>js/jquery-1.7.2.min.js"></script>

    <link rel="stylesheet" href="<?=$this->baseUrl();?>css/wax.css"/>

    <!-- Le styles -->
    <link rel="stylesheet" href="<?=$this->baseUrl();?>appcase/css/bootstrap.min.css"/>
    <?php if ($this->theme != '') { ?>
    <link rel="stylesheet" href="<?=$this->baseUrl();?>css/<?=$this->theme;?>.bootstrap.min.css"/>
    <?php } ?>
    <script src="<?=$this->baseUrl();?>js/bs-all.js"></script>

    <link rel="stylesheet" href="<?=$this->baseUrl();?>css/front.css"/>
    <script src="<?=$this->baseUrl();?>js/jquery.scrollTo.js"></script>
    <style type="text/css">
        body {
            padding-top: 40px; /* 40px to make the container go all the way to the bottom of the topbar */
        }

    </style>


</head>

<body>
<div id="fb-root"></div>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">

        <ul class="nav">
                <li><a href="<?=$this->baseUrl();?>"><?=$this->siteTitle();?></a></li>

            </ul>
            <?php if (!$this->loggedIn()) : ?>
			<?php if($this->allowRegister()) : ?>
				<form method="get" action="<?php echo $this->baseUrl();?>register" class="pull-right topform">
				<input class="btn blacktext btn-primary" name="topbtn" type="submit" value="Register"/>
				</form>
				&nbsp;
			<?php endif; ?>
            <form method="post" action="<?php echo $this->baseUrl();?>auth" class="pull-right topform">
                <input class="topinput input-small" type="text" name="username" placeholder="Username">

                <input class="topinput input-small" type="password" name="password" placeholder="Password">
                <input class="btn blacktext btn-primary" name="topbtn" type="submit" value="Sign in"/>
            </form>
            <?php else : ?>
            <div class="pull-right loggedin">
                Welcome <?php echo $this->loggedInAs()->username; ?>
                &nbsp;
                <?php if ($this->loggedIn()) : ?>
<!--                <a href="--><?//=$this->baseUrl();?><!--project">My Projects</a>-->
                <?php endif; ?>
                |
                <a href="<?php echo $this->baseUrl();?>auth/logout">Log out</a>
            </div>
            <?php endif; ?>


        </div>
    </div>
</div>

<div class="contentarea2">


    <div class="container">
        <?php echo $this->flashMessages();?>
        <div class="content">
            <?php if ($this->pageTitle != '') { ?>
            <div class="page-header">
                <h1><?php echo $this->pageTitle ? : "page"; ?>
                    <small><?php echo $this->pageSubTitle ? : ""; ?> </small>
                </h1>
            </div>
            <?php } else { ?>

            <?php } ?>

            <div class="row">

                <div class="span12">

                    <?php echo $this->layout()->content; ?>

                </div>
            </div>
        </div>


    </div>
    <!-- /container -->
</div>

<?=$this->footer();?>

<script>
    $(".alert").alert();
</script>


</body>
</html>
