<!DOCTYPE html>
<html lang="en">
  <head>
<meta name = "viewport" content = "width=300, initial-scale=1.0, user-scalable = yes">


      <script src="<?=$this->baseUrl();?>js/jquery-1.7.2.min.js"></script>

    <meta charset="utf-8">
    <title><?php echo $this->title;?></title>
    <meta name="description" content="<?php echo $this->description;?>">

      <script charset="UTF-8" type="text/javascript" src="http://ecn.dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=7.0"></script>

      <link rel="stylesheet" href="<?=$this->baseUrl();?>bootstrap/css/bootstrap.min.css"/>
      <link rel="stylesheet" href="<?=$this->baseUrl();?>bootstrap/css/bootstrap-responsive.min.css"/>
      <?php if($this->theme!='') { ?>
      <link rel="stylesheet" href="<?=$this->baseUrl();?>css/<?=$this->theme;?>.bootstrap.min.css"/>
          <?php } ?>
	<link rel="stylesheet" href="<?=$this->baseUrl();?>css/05_main.css"/>
    <script src="<?=$this->baseUrl();?>js/bootstrap-alert.js"></script>
  </head>

  <body>


    <div class="row">
<?php echo $this->flashMessagesMobile();?>
      <div id="mobilecontent" class="content">
	<?php echo $this->layout()->content; ?>
      </div>



    </div> <!-- /container -->
<script>
    $(".alert").alert();
</script>


  </body>
</html>
