<!DOCTYPE html>
<html lang="en">
<head>
<script type="text/javascript">var _sf_startpt=(new Date()).getTime()</script>
    <meta charset="utf-8">
    <title><?php echo $this->title;?></title>
    <meta name="description" content="<?php echo $this->description;?>">
    <meta name="author" content="">

    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <script src='<?=$this->baseUrl();?>js/wax6beta/ext/leaflet.js' type='text/javascript'></script>
    <script src='<?=$this->baseUrl();?>js/wax6beta/dist/wax.leaf.js' type='text/javascript'></script>
    <link href='<?=$this->baseUrl();?>js/wax6beta/ext/leaflet.css' rel='stylesheet' type='text/css'/>
    <link href='<?=$this->baseUrl();?>js/wax6beta/theme/controls.css' rel='stylesheet' type='text/css'/>
    <script src="<?=$this->baseUrl();?>js/jquery-1.7.2.min.js"></script>

    <link rel="stylesheet" href="<?=$this->baseUrl();?>css/wax.css"/>

    <!-- Le styles -->
    <link rel="stylesheet" href="<?=$this->baseUrl();?>appcase/css/bootstrap.min.css"/>
    <?php if ($this->theme != '') { ?>
    <link rel="stylesheet" href="<?=$this->baseUrl();?>css/<?=$this->theme;?>.bootstrap.min.css"/>
    <?php } ?>
    <script src="<?=$this->baseUrl();?>js/bs-all.js"></script>

    <link rel="stylesheet" href="<?=$this->baseUrl();?>css/front.css"/>
    <link rel="stylesheet" href="<?=$this->baseUrl();?>css/print.css"/>


</head>

<body>



<div class="contentarea2">


    <div class="container">
        <?php echo $this->flashMessages();?>
        <div class="content">
            <?php if ($this->pageTitle != '') { ?>
            <div class="page-header">
                <h1><?php echo $this->pageTitle ? : "page"; ?>
                    <small><?php echo $this->pageSubTitle ? : ""; ?> </small>
                </h1>
            </div>
            <?php } else { ?>

            <?php } ?>

            <div class="row">

                <div class="span12">

                    <?php echo $this->layout()->content; ?>

                </div>
            </div>
        </div>


    </div>
    <!-- /container -->
</div>

<?=$this->footerprinter();?>

<script>
    $(".alert").alert();
</script>

<script>
    window.print();
</script>
</body>
</html>
