<!DOCTYPE html>
<html lang="en">
<head>
<script type="text/javascript">var _sf_startpt=(new Date()).getTime()</script>
    <meta charset="utf-8">
    <title><?php echo $this->title;?></title>
    <meta name="description" content="<?php echo $this->description;?>">
    <meta name="author" content="">

    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <script src='<?=$this->baseUrl();?>js/wax6beta/ext/leaflet.js' type='text/javascript'></script>
    <script src='<?=$this->baseUrl();?>js/wax6beta/dist/wax.leaf.js' type='text/javascript'></script>
    <link href='<?=$this->baseUrl();?>js/wax6beta/ext/leaflet.css' rel='stylesheet' type='text/css'/>
    <link href='<?=$this->baseUrl();?>js/wax6beta/theme/controls.css' rel='stylesheet' type='text/css'/>
    <script src="<?=$this->baseUrl();?>js/jquery-1.7.2.min.js"></script>

    <link rel="stylesheet" href="<?=$this->baseUrl();?>css/wax.css"/>

    <!-- Le styles -->
    <link rel="stylesheet" href="<?=$this->baseUrl();?>appcase/css/bootstrap.min.css"/>
    <?php if ($this->theme != '') { ?>
    <link rel="stylesheet" href="<?=$this->baseUrl();?>css/<?=$this->theme;?>.bootstrap.min.css"/>
    <?php } ?>
    <script src="<?=$this->baseUrl();?>js/bs-all.js"></script>

    <link rel="stylesheet" href="<?=$this->baseUrl();?>css/front.css"/>
    <link rel="stylesheet" href="<?=$this->baseUrl();?>css/print.css"/>


    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-30933507-1']);
        _gaq.push(['_setDomainName', 'fieldflag.com']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script');
            ga.type = 'text/javascript';
            ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(ga, s);
        })();

    </script>
</head>

<body>



<div class="contentarea2">


    <div class="container">
        <?php echo $this->flashMessages();?>
        <div class="content">
            <?php if ($this->pageTitle != '') { ?>
            <div class="page-header">
                <h1><?php echo $this->pageTitle ? : "page"; ?>
                    <small><?php echo $this->pageSubTitle ? : ""; ?> </small>
                </h1>
            </div>
            <?php } else { ?>

            <?php } ?>

            <div class="row">

                <div class="span12">

                    <?php echo $this->layout()->content; ?>

                </div>
            </div>
        </div>


    </div>
    <!-- /container -->
</div>

<?=$this->footerprinter();?>

<script>
    $(".alert").alert();
</script>

<script type="text/javascript">
  var _sf_async_config = { uid: 9726, domain: 'fieldflag.com' };
  (function() {
    function loadChartbeat() {
      window._sf_endpt = (new Date()).getTime();
      var e = document.createElement('script');
      e.setAttribute('language', 'javascript');
      e.setAttribute('type', 'text/javascript');
      e.setAttribute('src',
        (("https:" == document.location.protocol) ? "https://a248.e.akamai.net/chartbeat.download.akamai.com/102508/" : "http://static.chartbeat.com/") +
        "js/chartbeat.js");
      document.body.appendChild(e);
    };
    var oldonload = window.onload;
    window.onload = (typeof window.onload != 'function') ?
      loadChartbeat : function() { oldonload(); loadChartbeat(); };
  })();
</script>
<script>
    window.print();
</script>
</body>
</html>
