


<div class="row centered">
  <h1>Whoops!</h1>
  <h2><?php echo $this->message ?></h2>
</div>

  <div class="row centered">
<img src="<?=$this->baseUrl();?>images/puppy1.jpg" alert="404 puppy1"/>
      </div>


<div class="row centered">
We couldn't find the page you were looking for,
    <br/>
    so here's a cute puppy to help make up for our mistake!
    <br/>
    <br/>

</div>


</body>
</html>
